version: "3"
services:
  db_loyalty:
    image: timescaledb:latest-pg12
    restart: always
    ports:
      - 5432:5432
    volumes:
      - './data:/var/lib/postgresql/data'
    environment:
      - POSTGRES_PASSWORD=admin
      - POSTGRES_HOST_AUTH_METHOD=trust
volumes:
  data_local: